### ISSUE TITLE
Zero return code when validation fails

### ISSUE THREAD

**Issue by peterjc** [enasequence/sequencetools#14]
With an internal error, the validator does return a non-zero error code, e.g.

```
$ touch empty.txt
$ java -jar embl-api-validator-1.1.146.jar empty.txt 
Exception in thread "main" java.sql.SQLException: java.lang.NullPointerException
	at uk.ac.ebi.embl.api.validation.EnaValidator.main(EnaValidator.java:171)
Caused by: java.lang.NullPointerException
	at uk.ac.ebi.embl.api.validation.helper.FileUtils.getFileType(FileUtils.java:144)
	at uk.ac.ebi.embl.api.validation.EnaValidator.init(EnaValidator.java:308)
	at uk.ac.ebi.embl.api.validation.EnaValidator.main(EnaValidator.java:165)
peter-cocks-mac-pro:tmp pjcock$ java -jar embl-api-validator-1.1.146.jar empty.txt ; echo "Return code $?"
Exception in thread "main" java.sql.SQLException: java.lang.NullPointerException
	at uk.ac.ebi.embl.api.validation.EnaValidator.main(EnaValidator.java:171)
Caused by: java.lang.NullPointerException
	at uk.ac.ebi.embl.api.validation.helper.FileUtils.getFileType(FileUtils.java:144)
	at uk.ac.ebi.embl.api.validation.EnaValidator.init(EnaValidator.java:308)
	at uk.ac.ebi.embl.api.validation.EnaValidator.main(EnaValidator.java:165)
Return code 1
```

However, when a fail fails validation a zero return code is given:

```
$ cat fake.embl 
ID fake
//
$ java -jar embl-api-validator-1.1.146.jar fake.embl ; echo "Return code $?"


Messages
ERROR: The entry has no sequence. (SequenceExistsCheck) 
ERROR: Citation information missing. (CitationExistsCheck_1) 
ERROR: Submitter references are mandatory in EMBL-BANK entries. (ReferenceCheck_1) 
ERROR: The entry has no sequence. (SequenceExistsCheck) 
ERROR: Entry has no "source" feature all entries must have a "source" feature. (SourceFeatureOnlyCheck-1) 
ERROR: Unknown line type: ID fake (FF.6)  line: 1
ERROR: Block DE must occur exactly once (FF.5)  line: 2
ERROR: Block ID must occur exactly once (FF.5)  line: 2
ERROR: Block AC must occur exactly once (FF.5)  line: 2

***FILE SUMMARY***
fake.embl - 1 entries, 1 failed entries, 9 errors, 0 fixes, 0 warnings & info

*** SUMMARY***
Fixed Entries:0
Failed Entries:1
Checked Entries:1
Unchanged Entries:1


Processed 1 entries in 0 seconds.

Return code 0
```

Following Unix conventions this should return a non-zero return code to indicate an error (this example failed validation with errors).

Ideally the validator would define the return codes via the help text, e.g. 0 on success, 1 for an internal error, 2 on bad arguments, 3 for validation failed.

This would allow using the validator within a script or pipeline to easily check if the file passed validation.

**Comment by kethireddy** [comment]
Added exit codes to the validator as suggested : 

0 SUCCESS
1 INTERNAL ERRORS (Exceptions)
2 INVALID INPUT
3 VALIDATION FAILURE

This change will be included in the next release of validator

**Comment by peterjc** [comment]
I can't see the changes on GitHub yet, but that sounds great - thank you!

**Comment by kethireddy** [comment]
Please try using latest version of validator :
https://mvnrepository.com/artifact/uk.ac.ebi.ena.sequence/embl-api-validator/1.1.147

**Comment by peterjc** [comment]
Thanks - that works nicely for the main use case of a file being accepted but failing validation:

```
$  java -jar embl-api-validator-1.1.147.jar fake.embl ; echo "Return code $?"


Messages
ERROR: The entry has no sequence. (SequenceExistsCheck) 
ERROR: Citation information missing. (CitationExistsCheck_1) 
ERROR: Submitter references are mandatory in EMBL-BANK entries. (ReferenceCheck_1) 
ERROR: Entry has no "source" feature all entries must have a "source" feature. (SourceFeatureOnlyCheck-1) 
ERROR: Unknown line type: ID fake (FF.6)  line: 1
ERROR: Block DE must occur exactly once (FF.5)  line: 2
ERROR: Block ID must occur exactly once (FF.5)  line: 2
ERROR: Block AC must occur exactly once (FF.5)  line: 2

***FILE SUMMARY***
fake.embl - 1 entries, 1 failed entries, 8 errors, 0 fixes, 0 warnings & info

*** SUMMARY***
Fixed Entries:0
Failed Entries:1
Checked Entries:1
Unchanged Entries:1


Processed 1 entries in 11 seconds.

Return code 3
```

Note the new version does not yet document the return codes in the help text:

```
$ java -jar embl-api-validator-1.1.147.jar --help
Invalid options
Usage: ena_validator <files> [options]
 
  Options:    -assembly        genome assembly entries (default: false)
    -de              Additional Fix :Adds/Fixes DE line(optional) (default: false)
    -f               File format(optional) Values:'embl','genbank','gff3','assembly' (default: embl)
    -filter          -filter <prefix> Store entries in <prefix>_good.txt and <prefix>_bad.txt files in the working directory. Entries with errors are stored in the bad file and entries without errors are stored in the good file. (optional)(default :false)
    -fix             Fixes entries in input files. Stores input files in 'original_files' folder. (optional) (default: false)
    -fix_diagnose    Creates 'diagnose' folder in the current directory with original entries in <filename>_origin file and the fixed entries in <filename>_fixed file. Only fixed entries will be stored in these files.(optional)  (default: false)
    -help            Displays available options (default: false)
    -l               Log level(optional) Values : 0(Quiet), 1(Summary), 2(Verbose) (default: 1)
    -lowmemory       Runs in low memory usage mode. Writes error logs but does not show message summary(optional) (default: false)
    -min_gap_length  minimum gap length to generate assembly_gap/gap features, use assembly flag to add assembly_gap features (default: 0)
    -prefix          Adds prefix to report files
    -r               Remote, is this being run outside the EBI(optional) (default: false)
    -skip            -skip <errorcode1>,<errorcode2>,... Ignore specified errors.(optional)(default:false) 
    -version         Displays implementation version of Jar (default: false)
    -wrap            Turns on line wrapping in flat file writing (optional)  (default: false)

```

**Comment by kethireddy** [comment]
fixed version of validator:  https://mvnrepository.com/artifact/uk.ac.ebi.ena.sequence/embl-api-validator/1.1.149

**Comment by peterjc** [comment]
Confirmed,

```
$ java -jar embl-api-validator-1.1.149.jar -help
Usage: ena_validator <files> [options]
 
  Options:    -assembly        genome assembly entries (default: false)
    -de              Additional Fix :Adds/Fixes DE line(optional) (default: false)
    -f               File format(optional) Values:'embl','genbank','gff3','assembly' (default: embl)
    -filter          -filter <prefix> Store entries in <prefix>_good.txt and <prefix>_bad.txt files in the working directory. Entries with errors are stored in the bad file and entries without errors are stored in the good file. (optional)(default :false)
    -fix             Fixes entries in input files. Stores input files in 'original_files' folder. (optional) (default: false)
    -fix_diagnose    Creates 'diagnose' folder in the current directory with original entries in <filename>_origin file and the fixed entries in <filename>_fixed file. Only fixed entries will be stored in these files.(optional)  (default: false)
    -help            Displays available options (default: false)
    -l               Log level(optional) Values : 0(Quiet), 1(Summary), 2(Verbose) (default: 1)
    -lowmemory       Runs in low memory usage mode. Writes error logs but does not show message summary(optional) (default: false)
    -min_gap_length  minimum gap length to generate assembly_gap/gap features, use assembly flag to add assembly_gap features (default: 0)
    -prefix          Adds prefix to report files
    -r               Remote, is this being run outside the EBI(optional) (default: false)
    -skip            -skip <errorcode1>,<errorcode2>,... Ignore specified errors.(optional)(default:false) 
    -version         Displays implementation version of Jar (default: false)
    -wrap            Turns on line wrapping in flat file writing (optional)  (default: false)

Return Codes: {0=SUCCESS, 1=INTERNAL ERROR, 2=INVALID INPUT, 3=VALIDATION ERROR}
```

Closing issue, thank you!
