### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by bastian-wur** [enasequence/sequencetools#6]
I can't figure out how to build the executables :(.

Due to the other issues and some googling I'm so far now:
- install gradle
- in the source directory, add a file gradle.properties with ossrhUsername and ossrhPassword . What should be the values of these? (and the format?)
- then execute in the directory "gradle build" (will take the build.gradle file, as it seems)
- right now it stops there and throws the following error:
```

:embl-api-core:signArchives FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':embl-api-core:signArchives'.
> Cannot perform signing task ':embl-api-core:signArchives' because it has no configured signatory

```

- I removed the signing from build.gradle (what is there to be signed, and how do i do this?)
- now the building stops at

```
uk.ac.ebi.embl.api.validation.check.feature.FeatureKeyCheckTest > testCheck_NoMandatoryQualifier STANDARD_OUT
    gene = gene name

uk.ac.ebi.embl.api.validation.check.genomeassembly.AssemblyFieldandValueCheckTest > testCheck_validRecord SKIPPED

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon3BeginPositionOne FAILED
    junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertTrue(Assert.java:31)
        at junit.framework.TestCase.assertTrue(TestCase.java:201)
        at uk.ac.ebi.embl.api.graphics.view.TranslationViewTest.compareImage(TranslationViewTest.java:61)
        at uk.ac.ebi.embl.api.graphics.view.TranslationViewTest.testStartCodon3BeginPositionOne(TranslationViewTest.java:389)

ETC ETC

Gradle Worker 1 finished executing tests.
Process 'Gradle Worker 1' finished with exit value 0 (state: SUCCEEDED)

1623 tests completed, 22 failed, 1 skipped
Finished generating test XML results (0.132 secs)
Generating HTML test report...
Finished generating test html results (0.531 secs)
:embl-api-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':embl-api-core:test'.
```

...so....er....what do I need to do?

**Comment by kethireddy** [comment]
Build instructions are added now : https://github.com/enasequence/sequencetools/wiki/Build-Instructions

**Comment by bastian-wur** [comment]
Thanks :).
But as already pointed out, this doesn't work out of the box.

Right now I can get the following output:
`bastian@SSB13002 ~/Tools/ena_embl_validator_17_08_2016 11:24:34$ git clone https://github.com/enasequence/sequencetools.git
Cloning into 'sequencetools'...
remote: Counting objects: 1600, done.
remote: Compressing objects: 100% (689/689), done.
remote: Total 1600 (delta 829), reused 1573 (delta 802), pack-reused 0
Receiving objects: 100% (1600/1600), 6.92 MiB | 511.00 KiB/s, done.
Resolving deltas: 100% (829/829), done.
Checking connectivity... done.
bastian@SSB13002 ~/Tools/ena_embl_validator_17_08_2016 11:24:59$ cd sequencetools/
bastian@SSB13002 ~/Tools/ena_embl_validator_17_08_2016/sequencetools 11:25:09$ gradlew build
bash: ./gradlew: Permission denied
bastian@SSB13002 ~/Tools/ena_embl_validator_17_08_2016/sequencetools 11:25:15$ gradlew build
: No such file or directory
bastian@SSB13002 ~/Tools/ena_embl_validator_17_08_2016/sequencetools 11:25:36$ gradle build

FAILURE: Build failed with an exception.

* Where:
Build file '/home/bastian/Tools/ena_embl_validator_17_08_2016/sequencetools/build.gradle' line: 84

* What went wrong:
A problem occurred evaluating root project 'sequencetools'.
> No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.527 secs
`

The ": No such file or directory" I get after making the gradlew bash file in the directory executable.
There must be something missing, I guess.

**Comment by kethireddy** [comment]
Could you please try using new build  : 	b2a6255

I think, gradle.properties file is missing in gradle home directory 
or 
properties missing in gradle.properties file

**Comment by bastian-wur** [comment]
Thanks :), this works now, but the build is still failing at a later stage.
Currently it fails at:
```

bastian@SSB13002 ~/Tools/ena_embl_validator_17_08_2016/sequencetools 13:22:52$ gradle build
:embl-api-core:compileJava UP-TO-DATE
:embl-api-core:processResources UP-TO-DATE
:embl-api-core:classes UP-TO-DATE
:embl-api-core:jar UP-TO-DATE
:embl-api-core:javadoc SKIPPED
:embl-api-core:javadocJar UP-TO-DATE
:embl-api-core:sourcesJar UP-TO-DATE
:embl-api-core:assemble UP-TO-DATE
:embl-api-core:compileTestJava UP-TO-DATE
:embl-api-core:processTestResources UP-TO-DATE
:embl-api-core:testClasses UP-TO-DATE
:embl-api-core:test

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon3BeginPositionOne FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon3BeginPositionTwo FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon3BeginPositionThree FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testShortTranslation1 FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testShortTranslation2 FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testShortTranslation3 FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon2BeginPositionThree FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon1BeginPositionOne FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon1BeginPositionTwo FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon1BeginPositionThree FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testCompositeLocation1 FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon2BeginPositionOne FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testStartCodon2BeginPositionTwo FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testCorrectTranslation1 FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testCorrectTranslation2 FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.TranslationViewTest > testCorrectTranslation3 FAILED
    junit.framework.AssertionFailedError at TranslationViewTest.java:61

uk.ac.ebi.embl.api.graphics.view.FeatureViewTest > testAsAssemblyLinesWithoutSequenceVersion FAILED
    junit.framework.AssertionFailedError at FeatureViewTest.java:45

uk.ac.ebi.embl.api.graphics.view.FeatureViewTest > testAsAssemblyLinesWithSequenceVersion FAILED
    junit.framework.AssertionFailedError at FeatureViewTest.java:45

uk.ac.ebi.embl.api.graphics.view.BasePairViewTest > testStartCodon1ExpandRight FAILED
    junit.framework.AssertionFailedError at BasePairViewTest.java:45

uk.ac.ebi.embl.api.graphics.view.BasePairViewTest > testStartCodon2ExpandRight FAILED
    junit.framework.AssertionFailedError at BasePairViewTest.java:45

uk.ac.ebi.embl.api.graphics.view.BasePairViewTest > testStartCodon3ExpandRight FAILED
    junit.framework.AssertionFailedError at BasePairViewTest.java:45

uk.ac.ebi.embl.api.graphics.view.BasePairViewTest > testNoTranslation FAILED
    junit.framework.AssertionFailedError at BasePairViewTest.java:45

1627 tests completed, 22 failed, 1 skipped
:embl-api-core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':embl-api-core:test'.
> There were failing tests. See the report at: file:///home/bastian/Tools/ena_embl_validator_17_08_2016/sequencetools/embl-api-core/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.12 secs

```

I thought it could be a problem with my java version, but no changes if I change between Java 1.7.0_80 , 1.8.0_72 and openJDK 1.6.0_39 .

The first exception reported is this:

```
Failed tests
testCompositeLocation1

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:201)
	at uk.ac.ebi.embl.api.graphics.view.TranslationViewTest.compareImage(TranslationViewTest.java:61)
	at uk.ac.ebi.embl.api.graphics.view.TranslationViewTest.testCompositeLocation1(TranslationViewTest.java:526)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:55)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:42)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:71)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:49)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:103)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

```

Is there any other dependency missing?
Just wondering because all the failed tests (22) are in uk.ac.ebi.embl.api.graphics.view , in uk.ac.ebi.embl.api.graphics.view.BasePairViewTest , uk.ac.ebi.embl.api.graphics.view.FeatureViewTest and uk.ac.ebi.embl.api.graphics.view.TranslationViewTest .

**Comment by kethireddy** [comment]
deleted unrelated classes from this project :  https://github.com/enasequence/sequencetools/commit/a33f08989cc8319dcda137902604e342a83e03c6

please try re-building the project with latest update

**Comment by bastian-wur** [comment]
Thanks, working now :).
