### ISSUE TITLE
Please document validator usage

### ISSUE THREAD

**Issue by satta** [enasequence/sequencetools#7]
I'm wondering what is the preferred command line frontend for the validator engine. If I grep for a `main`method in the source code, it looks like there is one in `uk.ac.ebi.embl.flatfile.example.FlatfileValidatorExample`, but it seems to be quite simplistic (just takes a filename as a parameter):
```
$ java -cp 'embl-api-ff/build/libs/embl-api-ff-1.1.130.jar:embl-api-core/build/libs/embl-api-core-1.1.130.jar:embl-api-ff/lib/*:embl-api-core/lib/*' uk.ac.ebi.embl.flatfile.example.FlatfileValidatorExample $PWD/Pv_Sal1_chr05.embl
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.lang.StringUtils.isAllUpperCase(Ljava/lang/String;)Z
	at uk.ac.ebi.embl.api.validation.fixer.feature.LocusTagValueFix.check(LocusTagValueFix.java:38)
	at uk.ac.ebi.embl.api.validation.fixer.feature.LocusTagValueFix.check(LocusTagValueFix.java:14)
	at uk.ac.ebi.embl.api.validation.plan.ValidationPlan.execute(ValidationPlan.java:196)
	at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.executeChecksandFixes(EmblEntryValidationPlan.java:165)
	at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.execute(EmblEntryValidationPlan.java:114)
	at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.execute(EmblEntryValidationPlan.java:143)
	at uk.ac.ebi.embl.flatfile.example.FlatfileValidatorExample.main(FlatfileValidatorExample.java:55)
```
I was unable to get it to run though -- it looks like `org.apache.commons.lang.StringUtils.isAllUpperCase()` is only available in commons-lang 2.5 or later [1], but this repo ships 2.1?

When I manually add a newer version to the classpath, I run into:
```
$ java -cp 'embl-api-ff/build/libs/embl-api-ff-1.1.130.jar:embl-api-core/build/libs/embl-api-core-1.1.130.jar:commons-lang-2.6/commons-lang-2.6.jar:embl-api-ff/lib/*:embl-api-core/lib/*' uk.ac.ebi.embl.flatfile.example.FlatfileValidatorExample $PWD/Pv_Sal1_chr05.embl
Exception in thread "main" uk.ac.ebi.embl.api.validation.ValidationEngineException: uk.ac.ebi.embl.api.validation.ValidationEngineException: java.lang.NullPointerException
	at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.execute(EmblEntryValidationPlan.java:120)
	at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.execute(EmblEntryValidationPlan.java:143)
	at uk.ac.ebi.embl.flatfile.example.FlatfileValidatorExample.main(FlatfileValidatorExample.java:55)
Caused by: uk.ac.ebi.embl.api.validation.ValidationEngineException: java.lang.NullPointerException
	at uk.ac.ebi.embl.api.validation.check.feature.EC_numberCheck.check(EC_numberCheck.java:51)
	at uk.ac.ebi.embl.api.validation.check.feature.EC_numberCheck.check(EC_numberCheck.java:25)
	at uk.ac.ebi.embl.api.validation.plan.ValidationPlan.execute(ValidationPlan.java:196)
	at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.executeChecksandFixes(EmblEntryValidationPlan.java:165)
	at uk.ac.ebi.embl.api.validation.plan.EmblEntryValidationPlan.execute(EmblEntryValidationPlan.java:115)
	... 2 more
Caused by: java.lang.NullPointerException
	at uk.ac.ebi.embl.api.validation.check.feature.EC_numberCheck.check(EC_numberCheck.java:47)
	... 6 more
```

It would be nice to have some documentation on how to run the validator front-end (or, even better, include the exact same interface that the validator on the EBI FTP site uses)

[1] http://libcommons-lang-java.sourcearchive.com/documentation/2.6-3/classorg_1_1apache_1_1commons_1_1lang_1_1StringUtils_a854bc29c009714ebe1d075de44bc24c9.html

**Comment by peterjc** [comment]
The main README file https://github.com/enasequence/sequencetools/blob/master/README.md has a usage section which links to https://www.ebi.ac.uk/ena/software/flat-file-validator which gives some basics.

Also at the command line you get some help on the command line API:

```
$ java -jar embl-api-validator-1.1.129.jar
Usage: ena_validator <files> [options]
 
  Options:    -assembly        genome assembly entries (default: false)
    -db              Database connection required for some checks and fixes.Valid databases : ENAPRO or ENADEV. Can only be used within EBI. (optional)(default :false)
    -de              Additional Fix :Adds/Fixes DE line(optional) (default: false)
    -f               File format(optional) Values:'embl','genbank','gff3','assembly' (default: embl)
    -filter          -filter <prefix> Store entries in <prefix>_good.txt and <prefix>_bad.txt files in the working directory. Entries with errors are stored in the bad file and entries without errors are stored in the good file. (optional)(default :false)
    -fix             Fixes entries in input files. Stores input files in 'original_files' folder. (optional) (default: false)
    -fix_diagnose    Creates 'diagnose' folder in the current directory with original entries in <filename>_origin file and the fixed entries in <filename>_fixed file. Only fixed entries will be stored in these files.(optional)  (default: false)
    -help            Displays available options (default: false)
    -l               Log level(optional) Values : 0(Quite),1(Summary),2(Verbose) (default: 1)
    -lowmemory       Runs in low memory usage mode. Writes error logs but does not show message summary(optional) (default: false)
    -min_gap_length  minimum gap length to generate assembly_gap/gap features, use assembly flag to add assembly_gap features (default: 0)
    -prefix          Adds prefix to report files
    -r               Remote, is this being run outside the EBI(optional) (default: false)
    -skip            -skip <errorcode1>,<errorcode2>,... Ignore specified errors.(optional)(default:false) 
    -version         Displays implementation version of Jar (default: false)
    -wrap            Turns on line wrapping in flat file writing (optional)  (default: false)
```

**Comment by satta** [comment]
Thanks @peterjc -- indeed I have used the `embl-api-validator-1.1.129.jar` you are mentioning before and I know its usage. What I was wondering about is how to build that jar from the source code in this repo:
```
$ gradle build
:embl-api-core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
:embl-api-core:processResources
:embl-api-core:classes
:embl-api-core:jar
:embl-api-core:javadoc SKIPPED
:embl-api-core:javadocJar
:embl-api-core:sourcesJar
:embl-api-core:assemble
:embl-api-core:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
:embl-api-core:processTestResources
:embl-api-core:testClasses
:embl-api-core:test
:embl-api-core:check
:embl-api-core:build
:embl-api-ff:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: /Users/satta/foss/sequencetools/embl-api-ff/src/main/java/uk/ac/ebi/embl/flatfile/reader/BufferedFileLineReader.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
:embl-api-ff:processResources
:embl-api-ff:classes
:embl-api-ff:jar
:embl-api-ff:javadoc SKIPPED
:embl-api-ff:javadocJar
:embl-api-ff:sourcesJar
:embl-api-ff:assemble
:embl-api-ff:compileTestJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:embl-api-ff:processTestResources UP-TO-DATE
:embl-api-ff:testClasses
:embl-api-ff:test
:embl-api-ff:check
:embl-api-ff:build

BUILD SUCCESSFUL

Total time: 26.084 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
$ find  . -name '*validator*jar'
$
```

**Comment by peterjc** [comment]
Issue #6 is about build instructions - this issue seemed to be about usage.

**Comment by satta** [comment]
Well, it _builds_ fine now... :)

It just looks like this source only seems to only include a basic command line interface that I think does not match the one you mention that's distributed on the ENA site (`embl-api-validator-*.jar`) and described at https://www.ebi.ac.uk/ena/software/flat-file-validator.

The point is that I'm trying to build from source only as I would like to package this software for Debian sooner or later.

**Comment by peterjc** [comment]
It is possible that not everything is in the Git repository yet - that would explain why I couldn't find the string in the validator tool to fix #8 myself?

**Comment by kethireddy** [comment]
Hi,

Sequencetools source code has two modules  :

1) embl-api-ff:  flat file parser(reader/writer)
2) embl-api-core:  flat file validation check/fixes 

Note : we cannot build fat/executable jars from it. 

embl-api-validator (source code is not published here) , which has validator command line program and it  uses embl-api-core/ff to build executable/fat jar.  Basically,It is a client for embl-api-core/ff.

I will add embl-api-validator module to sequencetools and push it to github .

I will remove "uk.ac.ebi.embl.flatfile.example.FlatfileValidatorExample" class from sequecetools to avoid confusion.

Sorry about the inconvenience.

Regards,
Kethi

**Comment by satta** [comment]
Thanks @kethireddy -- that's very helpful, especially including the CLI client module! I guess if it's not possible to build an executable jar, it's still possible to have a wrapper script that does the necessary long-ish direct class call.

**Comment by kethireddy** [comment]
Added validator client module to sequencetools i.e. embl-api-validator
gradle build should be able to generate Three Jars  : 

embl-api-ff ( non_executable Jar)
embl-api-core (non-executable Jar)
embl-api-validator  (executable Jar)

**Comment by satta** [comment]
Great, many thanks! I'm now able to build the validator jar and it is even executable via:
```
$ java -jar ./embl-api-validator/build/libs/embl-api-validator-1.1.131.jar                                                         [master] [1]
Usage: ena_validator <files> [options]

  Options:    -assembly        genome assembly entries (default: false)
    -de              Additional Fix :Adds/Fixes DE line(optional) (default: false)
    -f               File format(optional) Values:'embl','genbank','gff3','assembly' (default: embl)
    -filter          -filter <prefix> Store entries in <prefix>_good.txt and <prefix>_bad.txt files in the working directory. Entries with errors are stored in the bad file and entries without errors are stored in the good file. (optional)(default :false)
    -fix             Fixes entries in input files. Stores input files in 'original_files' folder. (optional) (default: false)
    -fix_diagnose    Creates 'diagnose' folder in the current directory with original entries in <filename>_origin file and the fixed entries in <filename>_fixed file. Only fixed entries will be stored in these files.(optional)  (default: false)
    -help            Displays available options (default: false)
    -l               Log level(optional) Values : 0(Quiet), 1(Summary), 2(Verbose) (default: 1)
    -lowmemory       Runs in low memory usage mode. Writes error logs but does not show message summary(optional) (default: false)
    -min_gap_length  minimum gap length to generate assembly_gap/gap features, use assembly flag to add assembly_gap features (default: 0)
    -prefix          Adds prefix to report files
    -r               Remote, is this being run outside the EBI(optional) (default: false)
    -skip            -skip <errorcode1>,<errorcode2>,... Ignore specified errors.(optional)(default:false)
    -version         Displays implementation version of Jar (default: false)
    -wrap            Turns on line wrapping in flat file writing (optional)  (default: false)
```
Excellent!
